apiVersion: "core.jikkou.io/v1"
kind: "KafkaTopicList"
metadata: {}
items:
  - metadata:
      name: 'pub.crm.customer.state.v1'
    spec:
      partitions: 2
      replicas: 3
      configs:
        cleanup.policy: compact
        segment.ms: 100
        delete.retention.ms: 100
        min.cleanable.dirty.ratio: 0.001

