POST localhost:29000/api/cardHolders
Content-Type: application/json

{
  "id": "cad4e633-d23e-9e95-97bc-909e7fa83e7q",
  "firstName": "Peter",
  "lastName": "Muster",
  "emailAddress": "cher.turner@hotmail.com",
  "phoneNumber": "+1 413-925-9346",
  "preferredContact": "phone",
  "segment": "gold",
  "card": {
    "number": "6524-2211-7337-4988",
    "type": "discover",
    "expiryDate": "2028-08-18"
  },
  "avgTransactionAmount": 175,
  "addresses": [
    {
      "street": "Sharda Corners",
      "zipCode": "92666",
      "city": "Prohaskaside",
      "state": "Hawaii"
    },
    {
      "street": "Garth Causeway",
      "zipCode": "79086",
      "city": "Sumikoberg",
      "state": "Texas"
    },
    {
      "street": "Taylor Route",
      "zipCode": "68794",
      "city": "East Thaddeus",
      "state": "Arkansas"
    }
  ],
  "usualCountries": ["CH", "BE"]
}